networks:
  default:
    driver: bridge
    enable_ipv6: false

volumes:
  postgres_data:
  redis_data:
  loki-data: {}
  grafana-data: {}

services:
  sentinel:
    build: .
    env_file:
      - ./cmd/.env
    container_name: sentinel
    ports:
      - "0.0.0.0:8080:8080" # make sure that container port is the same in config
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./cmd/.env:/sentinel/.env
      - ./cmd/sentinel.config.yaml:/sentinel/sentinel.config.yaml
      - ./cmd/RBAC.json:/sentinel/RBAC.json

  postgres:
    image: postgres:17.2
    env_file:
      - ./cmd/.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DB_USER} -d $${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2.5-alpine
    ports:
      - "6379"
    volumes:
      - redis_data:/data
    networks:
      - default
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5
  loki:
    image: grafana/loki:3.5.0
    ports:
      - "3100:3100"
    volumes:
      - ./cmd/loki-config.yaml:/etc/loki/loki-config.yaml
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped

  promtail:
    image: grafana/promtail:3.5.0
    volumes:
      - /var/log:/var/log
      - ./cmd/promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - loki
    restart: unless-stopped

