### HTTP ###
http-port: 8050

http-secured: false

http-allowed-origins:
  - "http://127.0.0.1:4321"

### DATABASE ###
db-default-queuery-timeout: 5s

### AUTHENTICATION ###
access-token-ttl: 10m

refresh-token-ttl: 336h # 14 days

### CACHE ###
cache-socket-timeout: 3s

cache-operation-timeout: 1s

cache-ttl: 0

### DEBUG ####
debug-mode: true

debug-safe-db-scans: false

### APP ###
service-id: cb663674-803e-4b06-bfeb-87c5cc86383e

is-login-email: true

user-activation-token-ttl: 24h

